# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usbhid" "uas" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" 
  ];
  boot.extraModulePackages = [ ];
  boot.blacklistedKernelModules = [];
  
  fileSystems."/" =
    { device = "/dev/disk/by-uuid/6df98b46-e730-4e5c-8e8c-0e0c2d9570cc";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-20cdc752-b82e-4994-b71d-31e9dd4ae785".device = "/dev/disk/by-uuid/20cdc752-b82e-4994-b71d-31e9dd4ae785";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/1F5B-7B5D";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/47d7d501-8565-4f84-b066-f531abd00b46"; }
    ];


  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp2s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp3s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
